#!/bin/bash
#260871813
#Elias Tamraz
if [ $# -lt 2 ] #check enough arguments
then
  echo "Error: Wrong number of
arguments. Please type ./mkproj ARGUMENT OWNER. The argument is the
name of the project. The OWNER is the user name the project belongs to."
  exit 1
fi
if [ ! -d Projects ] #check if directory exists
then
mkdir Projects
fi
cd Projects
if [ -d $1 ]
then
echo "Error: The project name has already been used. Please select another project name and try again."
exit 2
fi
mkdir $1 #make directory for new project
cd $1
mkdir archive
mkdir backup
mkdir docs
mkdir assets
mkdir database
mkdir source
ls -R
cd docs
touch readme.txt
echo -ne "Created by: $2\n" >> readme.txt

cat readme.txt
